Loading training set...
C:\Users\kytom\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\data\sampler.py:64: UserWarning: `data_source` argument is not used and will be removed in 2.2.0.You may still have custom implementation that utilizes it.
  warnings.warn("`data_source` argument is not used and will be removed in 2.2.0."

Num images:  1
Image shape: [4, 224, 224]
Label shape: [0]

Constructing networks...
Traceback (most recent call last):
  File "C:\Users\kytom\Desktop\UST\swin_gan\SwinGAN\stylegan2\train.py", line 566, in <module>
    main() # pylint: disable=no-value-for-parameter
    ^^^^^^
  File "C:\Users\kytom\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kytom\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\kytom\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kytom\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kytom\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kytom\Desktop\UST\swin_gan\SwinGAN\stylegan2\train.py", line 559, in main
    subprocess_fn(rank=0, args=args, temp_dir=temp_dir, swin=swin)
  File "C:\Users\kytom\Desktop\UST\swin_gan\SwinGAN\stylegan2\train.py", line 386, in subprocess_fn
    training_loop.training_loop(rank=rank, **args, swin=swin)
  File "C:\Users\kytom\Desktop\UST\swin_gan\SwinGAN\stylegan2\training\training_loop.py", line 178, in training_loop
    dnnlib.util.construct_class_by_name(**G_kwargs, **common_kwargs)
  File "C:\Users\kytom\Desktop\UST\swin_gan\SwinGAN\stylegan2\dnnlib\util.py", line 289, in construct_class_by_name
    return call_func_by_name(*args, func_name=class_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kytom\Desktop\UST\swin_gan\SwinGAN\stylegan2\dnnlib\util.py", line 284, in call_func_by_name
    return func_obj(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kytom\Desktop\UST\swin_gan\SwinGAN\stylegan2\torch_utils\persistence.py", line 104, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\kytom\Desktop\UST\swin_gan\SwinGAN\stylegan2\training\networks.py", line 695, in __init__
    self.synthesis = SynthesisNetwork(
                     ^^^^^^^^^^^^^^^^^
  File "C:\Users\kytom\Desktop\UST\swin_gan\SwinGAN\stylegan2\torch_utils\persistence.py", line 104, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\kytom\Desktop\UST\swin_gan\SwinGAN\stylegan2\training\networks.py", line 619, in __init__
    assert img_resolution >= 4 and img_resolution & (img_resolution - 1) == 0
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
